#!/usr/bin/env python3
"""
Visualization script for Problem 2: Line Fitting Comparison (OLS vs TLS)
Reads CSV files generated by problem2.cpp and creates comparison plots.
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from pathlib import Path

def plot_line_fitting_comparison():
    """
    Create a 2x2 subplot comparing OLS and TLS line fitting for 4 test cases.
    """
    # Test case configurations (normals used in C++ code)
    test_cases = [
        {"name": "case1", "normal": "[1, 0]", "description": "Vertical line"},
        {"name": "case2", "normal": "[0.6, 0.8]", "description": "Diagonal line"},
        {"name": "case3", "normal": "[-0.6, 0.8]", "description": "Diagonal line"},
        {"name": "case4", "normal": "[0, 1]", "description": "Horizontal line"}
    ]

    # Create figure with 2x2 subplots
    fig, axes = plt.subplots(2, 2, figsize=(14, 12))
    axes = axes.flatten()

    # Data directory (CSV files are in build/ directory)
    data_dir = Path("build")

    for idx, case in enumerate(test_cases):
        ax = axes[idx]
        case_name = case["name"]

        # Read CSV files
        points = pd.read_csv(data_dir / f"{case_name}_points.csv")
        ols_line = pd.read_csv(data_dir / f"{case_name}_ols.csv")
        tls_line = pd.read_csv(data_dir / f"{case_name}_tls.csv")

        # Plot noisy points
        ax.scatter(points['x'], points['y'], c='gray', alpha=0.5, s=20,
                   label='Noisy data points', zorder=1)

        # Plot OLS fitted line (thick dashed blue)
        ax.plot(ols_line['x'], ols_line['y'], 'b--', linewidth=5,
                label='OLS fit (dashed blue)', zorder=2)

        # Plot TLS fitted line (thinner solid red)
        ax.plot(tls_line['x'], tls_line['y'], 'r-', linewidth=2,
                label='TLS fit (solid red)', zorder=3)

        # Formatting
        ax.set_xlabel('x', fontsize=11)
        ax.set_ylabel('y', fontsize=11)
        ax.set_title(f'Case {idx+1}: Normal = {case["normal"]}ᵀ\n({case["description"]})',
                     fontsize=12, fontweight='bold')
        ax.legend(loc='best', fontsize=9)
        ax.grid(True, alpha=0.3)
        ax.set_aspect('equal', adjustable='box')

        # Set reasonable axis limits
        ax.set_xlim(-6, 6)
        ax.set_ylim(-6, 6)

    plt.tight_layout()

    # Save figure
    output_path = Path("problem2_plots.png")
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    print(f"Figure saved to: {output_path.absolute()}")
    plt.close()

def plot_individual_cases():
    """
    Create individual high-resolution plots for each test case.
    """
    # Test case configurations (normals used in C++ code)
    test_cases = [
        {"name": "case1", "normal": "[1, 0]", "description": "Vertical line", "n0": 1.0},
        {"name": "case2", "normal": "[0.6, 0.8]", "description": "Diagonal line", "n0": 1.0},
        {"name": "case3", "normal": "[-0.6, 0.8]", "description": "Diagonal line", "n0": 1.0},
        {"name": "case4", "normal": "[0, 1]", "description": "Horizontal line", "n0": 1.0}
    ]

    # Data directory (CSV files are in build/ directory)
    data_dir = Path("build")

    for idx, case in enumerate(test_cases):
        case_name = case["name"]

        # Read CSV files
        points = pd.read_csv(data_dir / f"{case_name}_points.csv")
        ols_line = pd.read_csv(data_dir / f"{case_name}_ols.csv")
        tls_line = pd.read_csv(data_dir / f"{case_name}_tls.csv")

        # Create individual figure
        fig, ax = plt.subplots(figsize=(8, 8))

        # Plot noisy points
        ax.scatter(points['x'], points['y'], c='gray', alpha=0.5, s=30,
                   label='Noisy data points', zorder=1)

        # Plot OLS fitted line (thick dashed blue)
        ax.plot(ols_line['x'], ols_line['y'], 'b--', linewidth=5,
                label='OLS fit (dashed blue)', zorder=2)

        # Plot TLS fitted line (thinner solid red)
        ax.plot(tls_line['x'], tls_line['y'], 'r-', linewidth=2,
                label='TLS fit (solid red)', zorder=3)

        # Formatting
        ax.set_xlabel('x', fontsize=12)
        ax.set_ylabel('y', fontsize=12)
        ax.set_title(f'Case {idx+1}: Normal = {case["normal"]}ᵀ\n({case["description"]})',
                     fontsize=14, fontweight='bold')
        ax.legend(loc='best', fontsize=11)
        ax.grid(True, alpha=0.3)
        ax.set_aspect('equal', adjustable='box')

        # Set reasonable axis limits
        ax.set_xlim(-6, 6)
        ax.set_ylim(-6, 6)

        # Add ground truth text box
        textstr = f'Ground Truth:\nn = {case["normal"]}ᵀ\nn₀ = {case["n0"]}'
        props = dict(boxstyle='round', facecolor='wheat', alpha=0.8)
        ax.text(0.05, 0.95, textstr, transform=ax.transAxes, fontsize=11,
                verticalalignment='top', bbox=props)

        # Save individual plot
        output_path = Path(f"{case_name}.png")
        plt.savefig(output_path, dpi=300, bbox_inches='tight')
        print(f"Individual plot saved: {output_path.absolute()}")
        plt.close()

if __name__ == "__main__":
    print("Generating Problem 2 visualization...")
    plot_line_fitting_comparison()
    print("\nGenerating individual case plots...")
    plot_individual_cases()
   
   
